/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type NewsCategory = {
  _id: string;
  _type: "newsCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Color>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  category?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "newsCategory";
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  display?: boolean;
};

export type Candidate = {
  _id: string;
  _type: "candidate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullname?: string;
  email?: string;
  job?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "jobDomain";
  };
  resume?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type JobCategory = {
  _id: string;
  _type: "jobCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category?: "Business & Technology Integration" | "Information Technology Operations" | "Solution Architecture & Planning" | "Consulting" | "Software Engineering" | "Technology & Information Architectures" | "Data & AI";
  type?: "Freelance" | "Full Time" | "Internship" | "Part Time" | "Temporary";
};

export type Job = {
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  job_domain?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "jobDomain";
  };
  job_type?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "jobType";
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Color>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  qualifications?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Color>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  display?: boolean;
};

export type JobType = {
  _id: string;
  _type: "jobType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type JobDomain = {
  _id: string;
  _type: "jobDomain";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type AskQuestion = {
  _id: string;
  _type: "askQuestion";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  card?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
};

export type Carrers = {
  _id: string;
  _type: "carrers";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
};

export type TelecommunicationsIndustries = {
  _id: string;
  _type: "telecommunicationsIndustries";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  title_section?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type FinancialIndustries = {
  _id: string;
  _type: "financialIndustries";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  title_section?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type InsuranceIndustries = {
  _id: string;
  _type: "insuranceIndustries";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  title_section?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type GovernmentIndustries = {
  _id: string;
  _type: "governmentIndustries";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  title_section?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type CyberServices = {
  _id: string;
  _type: "cyberServices";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  title_section?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type ArtificialServices = {
  _id: string;
  _type: "artificialServices";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  title_section?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type ProjectServices = {
  _id: string;
  _type: "projectServices";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  title_section?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type ManagedServices = {
  _id: string;
  _type: "managedServices";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  title_section?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type TechnologiesServices = {
  _id: string;
  _type: "technologiesServices";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  title_section?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type ApplicationServices = {
  _id: string;
  _type: "applicationServices";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  title_section?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card_primary?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
  card_secondary?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type ConsultingServices = {
  _id: string;
  _type: "consultingServices";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  title_section_primary?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card_primary?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
  title_section_secondary?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card_primary?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
  card_secondary?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card_primary?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
  home_isga?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "chooseISGA";
  };
  card_secondary?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type ChooseISGA = {
  _id: string;
  _type: "chooseISGA";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  description?: Array<string>;
  cards?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
};

export type Simple = {
  _id: string;
  _type: "simple";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: Array<string>;
  subtitle?: Array<string>;
  description?: Array<string>;
};

export type Card = {
  _id: string;
  _type: "card";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  svg_path?: string;
  subtitle?: Array<string>;
  description?: Array<string>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Landing = {
  _id: string;
  _type: "landing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: Array<string>;
  subtitle?: Array<string>;
  description?: Array<string>;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "landingCategories";
  }>;
  author?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type LandingCategories = {
  _id: string;
  _type: "landingCategories";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | Geopoint | Slug | NewsCategory | News | Candidate | SanityFileAsset | JobCategory | Job | JobType | JobDomain | AskQuestion | Contact | Carrers | TelecommunicationsIndustries | FinancialIndustries | InsuranceIndustries | GovernmentIndustries | CyberServices | ArtificialServices | ProjectServices | ManagedServices | TechnologiesServices | ApplicationServices | ConsultingServices | About | Home | ChooseISGA | Simple | Card | Landing | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | LandingCategories | Color | RgbaColor | HsvaColor | HslaColor;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../client/src/sanity/lib/pages/about.ts
// Variable: query
// Query: *[_type == 'about'][0]
export type QueryResult = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  landing?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "landing";
  };
  content?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "simple";
  };
  card_primary?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
  card_secondary?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "card";
  }>;
} | null;

// Source: ../client/src/sanity/lib/pages/queries.ts
// Variable: homeQuery
// Query: *[_type == 'home'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },       content -> {          _id,          title[],          subtitle[],          description[]        },        home_isga -> {          _id,          image {            asset -> { url }           },          title,          description,          cards []-> {            _id,            title,            subtitle,            description,            image {              asset -> { url }             },            svg_path,          }         },           card_primary []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },                 card_secondary []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },     }
export type HomeQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  home_isga: {
    _id: string;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    title: string | null;
    description: Array<string> | null;
    cards: Array<{
      _id: string;
      title: string | null;
      subtitle: Array<string> | null;
      description: Array<string> | null;
      image: {
        asset: {
          url: string | null;
        } | null;
      } | null;
      svg_path: string | null;
    }> | null;
  } | null;
  card_primary: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
  card_secondary: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: aboutQuery
// Query: *[_type == 'about'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },       content -> {          _id,          title[],          subtitle[],          description[]        },           card_primary []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },                 card_secondary []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },     }
export type AboutQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card_primary: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
  card_secondary: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: consultingQuery
// Query: *[_type == 'consultingServices'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },                     title_section_primary -> {          _id,          title[],          subtitle[],          description[],        },        content -> {          _id,          title[],          subtitle[],          description[],        },        content -> {          _id,          title[],          subtitle[],          description[],        },                title_section_secondary -> {          _id,          title[],          subtitle[],          description[],        },           card_primary []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },                 card []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },     }
export type ConsultingQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  title_section_primary: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  title_section_secondary: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card_primary: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
  card: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: applicationQuery
// Query: *[_type == 'applicationServices'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },              content -> {         _id,         title[],         subtitle[],         description[],        },       title_section -> {          _id,          title[],          subtitle[],          description[],        },                  card_primary []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },                    card_secondary []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },    }
export type ApplicationQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  title_section: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card_primary: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
  card_secondary: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: technologiesQuery
// Query: *[_type == 'technologiesServices'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },                     title_section -> {          _id,          title[],          subtitle[],          description[],        },                 content -> {          _id,          title[],          subtitle[],          description[],        },           card []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },        }
export type TechnologiesQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  title_section: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: managedQuery
// Query: *[_type == 'managedServices'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },                     title_section -> {          _id,          title[],          subtitle[],          description[],        },                 content -> {          _id,          title[],          subtitle[],          description[],        },            card []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },            }
export type ManagedQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  title_section: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: projectQuery
// Query: *[_type == 'projectServices'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },                     title_section -> {          _id,          title[],          subtitle[],          description[],        },                 content -> {          _id,          title[],          subtitle[],          description[],        },            card []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },            }
export type ProjectQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  title_section: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: artificialQuery
// Query: *[_type == 'artificialServices'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },                     title_section -> {          _id,          title[],          subtitle[],          description[],        },                 content -> {          _id,          title[],          subtitle[],          description[],        },            card []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },            }
export type ArtificialQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  title_section: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: cyberQuery
// Query: *[_type == 'cyberServices'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },                     title_section -> {          _id,          title[],          subtitle[],          description[],        },                 content -> {          _id,          title[],          subtitle[],          description[],        },            card []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },            }
export type CyberQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  title_section: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  content: null;
  card: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: governmentQuery
// Query: *[_type == 'governmentIndustries'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },                     title_section -> {          _id,          title[],          subtitle[],          description[],        },                 content -> {          _id,          title[],          subtitle[],          description[],        },            card []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },            }
export type GovernmentQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  title_section: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: insuranceQuery
// Query: *[_type == 'insuranceIndustries'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },                     title_section -> {          _id,          title[],          subtitle[],          description[],        },                 content -> {          _id,          title[],          subtitle[],          description[],        },             card []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },            }
export type InsuranceQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  title_section: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: financialQuery
// Query: *[_type == 'financialIndustries'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },                     title_section -> {          _id,          title[],          subtitle[],          description[],        },                 content -> {          _id,          title[],          subtitle[],          description[],        },             card []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },            }
export type FinancialQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  title_section: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: telecommunicationQuery
// Query: *[_type == 'telecommunicationsIndustries'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },                     title_section -> {          _id,          title[],          subtitle[],          description[],        },                 content -> {          _id,          title[],          subtitle[],          description[],        },             card []-> {          _id,          title,          subtitle,          description,          image {            asset -> { url }           },          svg_path,               },            }
export type TelecommunicationQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  title_section: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: carrersQuery
// Query: *[_type == 'carrers'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },               }
export type CarrersQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
}>;
// Variable: contactQuery
// Query: *[_type == 'contact'] {      landing -> {        _id,        title[],        subtitle[],        description[],        image {          asset -> { url }        },        author,      },      content -> {        _id,        title[],        subtitle[],        description[],      },      card []-> {        _id,        title,        subtitle,        description,        image {          asset -> { url }         },        svg_path,             },                }
export type ContactQueryResult = Array<{
  landing: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    author: string | null;
  } | null;
  content: {
    _id: string;
    title: Array<string> | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
  } | null;
  card: Array<{
    _id: string;
    title: string | null;
    subtitle: Array<string> | null;
    description: Array<string> | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
    svg_path: string | null;
  }> | null;
}>;
// Variable: jobQuery
// Query: *[_type == 'job' && display == true] {      _updatedAt,      title,      job_domain -> {        _id,        title      },      job_type -> {        _id,        title      },      description,      qualifications,      display    }
export type JobQueryResult = Array<{
  _updatedAt: string;
  title: string | null;
  job_domain: {
    _id: string;
    title: string | null;
  } | null;
  job_type: {
    _id: string;
    title: string | null;
  } | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Color>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  qualifications: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Color>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  display: boolean | null;
}>;
// Variable: jobDomains
// Query: *[_type == 'jobDomain'] {      title,      _id,      _createdAt,      _rev,      _type,      _updatedAt    }
export type JobDomainsResult = Array<{
  title: string | null;
  _id: string;
  _createdAt: string;
  _rev: string;
  _type: "jobDomain";
  _updatedAt: string;
}>;
// Variable: jobTypes
// Query: *[_type == 'jobType'] {      title,      _id,      _createdAt,      _rev,      _type,      _updatedAt    }
export type JobTypesResult = Array<{
  title: string | null;
  _id: string;
  _createdAt: string;
  _rev: string;
  _type: "jobType";
  _updatedAt: string;
}>;
// Variable: newsCategoriesQuery
// Query: *[_type == 'newsCategory'] {        _id,      title,    }
export type NewsCategoriesQueryResult = Array<{
  _id: string;
  title: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n       *[_type == 'about'][0]\n        ": QueryResult;
    "\n    *[_type == 'home'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n\n       content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[]\n        },\n\n        home_isga -> {\n          _id,\n          image {\n            asset -> { url } \n          },\n          title,\n          description,\n          cards []-> {\n            _id,\n            title,\n            subtitle,\n            description,\n            image {\n              asset -> { url } \n            },\n            svg_path,\n          } \n        },\n    \n       card_primary []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },\n        \n         card_secondary []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        }, \n\n    }   \n  ": HomeQueryResult;
    "\n    *[_type == 'about'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n\n       content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[]\n        },\n    \n       card_primary []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },\n        \n         card_secondary []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        }, \n\n    }   \n  ": AboutQueryResult;
    "\n    *[_type == 'consultingServices'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n              \n       title_section_primary -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        },\n\n        content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        },\n\n        content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        },\n        \n        title_section_secondary -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        },\n    \n       card_primary []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },\n        \n         card []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        }, \n\n    }   \n  ": ConsultingQueryResult;
    "\n    *[_type == 'applicationServices'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n       \n       content -> {\n         _id,\n         title[],\n         subtitle[],\n         description[],\n        },\n\n       title_section -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        },       \n    \n       card_primary []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },    \n        \n        card_secondary []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },\n    }   \n  ": ApplicationQueryResult;
    "\n    *[_type == 'technologiesServices'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n              \n       title_section -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n        \n        content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        },\n    \n       card []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },    \n\n    }   \n  ": TechnologiesQueryResult;
    "\n    *[_type == 'managedServices'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n              \n       title_section -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n        \n        content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        },\n    \n        card []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },        \n    }   \n  ": ManagedQueryResult;
    "\n    *[_type == 'projectServices'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n              \n       title_section -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n        \n        content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        },\n    \n        card []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },        \n    }   \n  ": ProjectQueryResult;
    "\n    *[_type == 'artificialServices'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n              \n       title_section -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n        \n        content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        },\n    \n        card []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },        \n    }   \n  ": ArtificialQueryResult;
    "\n    *[_type == 'cyberServices'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n              \n       title_section -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n        \n        content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        },\n    \n        card []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },        \n    }   \n  ": CyberQueryResult;
    "\n    *[_type == 'governmentIndustries'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n              \n       title_section -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n        \n        content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        },\n    \n        card []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },        \n    }   \n  ": GovernmentQueryResult;
    "\n    *[_type == 'insuranceIndustries'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n              \n       title_section -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n        \n        content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n    \n        card []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },        \n    }   \n  ": InsuranceQueryResult;
    "\n    *[_type == 'financialIndustries'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n              \n       title_section -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n        \n        content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n    \n        card []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },        \n    }   \n  ": FinancialQueryResult;
    "\n    *[_type == 'telecommunicationsIndustries'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n              \n       title_section -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n        \n        content -> {\n          _id,\n          title[],\n          subtitle[],\n          description[],\n        }, \n    \n        card []-> {\n          _id,\n          title,\n          subtitle,\n          description,\n          image {\n            asset -> { url } \n          },\n          svg_path,       \n        },        \n    }   \n  ": TelecommunicationQueryResult;
    "\n    *[_type == 'carrers'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n           \n    }   \n  ": CarrersQueryResult;
    "\n    *[_type == 'contact'] {\n      landing -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n        image {\n          asset -> { url }\n        },\n        author,\n      },\n\n      content -> {\n        _id,\n        title[],\n        subtitle[],\n        description[],\n      },\n\n      card []-> {\n        _id,\n        title,\n        subtitle,\n        description,\n        image {\n          asset -> { url } \n        },\n        svg_path,       \n      }, \n           \n    }   \n  ": ContactQueryResult;
    "\n    *[_type == 'job' && display == true] {\n      _updatedAt,\n      title,\n      job_domain -> {\n        _id,\n        title\n      },\n      job_type -> {\n        _id,\n        title\n      },\n      description,\n      qualifications,\n      display\n\n    }\n  ": JobQueryResult;
    "\n    *[_type == 'jobDomain'] {\n      title,\n      _id,\n      _createdAt,\n      _rev,\n      _type,\n      _updatedAt\n    }  \n  ": JobDomainsResult;
    "\n    *[_type == 'jobType'] {\n      title,\n      _id,\n      _createdAt,\n      _rev,\n      _type,\n      _updatedAt\n    }  \n  ": JobTypesResult;
    "\n    *[_type == 'newsCategory'] {  \n      _id,\n      title,\n    }\n  ": NewsCategoriesQueryResult;
  }
}
