import type { Metadata } from "next";
import "./globals.css";
import { Navbar, Footer, DisableDraftMode, ScrollTop } from "@/components";
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isEnabled } = await draftMode();

  // Check if the current request is a Sanity Studio preview
  const isSanityStudioRequest =
    typeof window !== "undefined" &&
    window.location.pathname.includes("/studio");

  console.log("Draft Mode Enabled:", isEnabled);
  // console.log("Sanity Studio Request:", isSanityStudioRequest);

  return (
    <html lang="en">
      <body>
        {/* Conditionally render VisualEditing */}

        {isEnabled && (
          <>
            <DisableDraftMode />
            <VisualEditing />
          </>
        )}
        <SanityLive />
        <Navbar />
        {children}
        <div className="pt-20">
          <Footer />
          <ScrollTop />
        </div>
      </body>
    </html>
  );
}
