import type { Metadata } from "next";
import "./globals.css";
import { Navbar, Footer } from "@/components";
import { BackgroundProvider } from "@/context/BackgroundContext";
import { SanityLive } from "@/sanity/lib/live";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <BackgroundProvider>
      <html lang="en">
        <body>
          <Navbar />
          {children}
          <div className="pt-20">
            <Footer />
          </div>
          <SanityLive />
        </body>
      </html>
    </BackgroundProvider>
  );
}
