import type { Metadata } from "next";
import "./globals.css";
import { Navbar, Footer } from "@/components";
import { BackgroundProvider } from "@/context/BackgroundContext";
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <BackgroundProvider>
    <html lang="en">
      <body>
        {(await draftMode()).isEnabled && <VisualEditing />}
        {/* <VisualEditing /> */}
        {/* <VisualEditing zIndex={1000} /> */}
        <SanityLive />
        <Navbar />
        {children}
        <div className="pt-20">
          <Footer />
        </div>
      </body>
    </html>
    // </BackgroundProvider>
  );
}
